@startuml

!include type.pu
!include astNode.pu

class VoidType
class IntType
class RealType
class CharType
class ArrayType
class FunctionType
class RecordType
class RecordField
class VarDefinition
class ErrorType

VarDefinition : String: name
VarDefinition : int: offset
ArrayType : int: size
RecordField : String: name
RecordField : int: offset
ErrorType : String: message

ASTNode <|.. Type

Type <|.. VoidType
Type <|.. IntType
Type <|.. RealType
Type <|.. CharType

Type <|.. ArrayType
ArrayType --> "1" Type

Type <|. FunctionType
Type "1" <--o FunctionType : return
VarDefinition "0..*" <--o FunctionType : arguments
Type "1" <--o  VarDefinition

Type <|.. RecordType
RecordType o--> "1..*" RecordField
ASTNode <|.. RecordField
RecordField --> "1" Type

Type <|.. ErrorType

@enduml

